

### Добавление пользователя
###
POST http://localhost:9999/api/users
Content-Type: application/json

{
  "login":"user1",
  "password":"pass1",
  "roles":"{ADMIN USER}"
}

### Добавление кривого пользователя
###
POST http://localhost:9999/api/users
Content-Type: application/json

{
  "login":"",
  "password":"pass1"
}

### Кривой URL
###
POST http://localhost:9999/api/userrrr
Content-Type: application/json

{
  "login":"user1",
  "password":"pass1"
}

### Запрос токена
###
POST http://localhost:9999/api/token
Content-Type: application/json

{
  "login":"user1",
  "password":"pass1"
}