

### Добавление пользователя
###
POST http://localhost:9999/api/users
Content-Type: application/json

{
  "login":"user5",
  "password":"pass1",
  "roles":"{ADMIN USER}"
}

### Добавление пользователя
###
POST http://localhost:9999/api/users
Content-Type: application/json

{
  "login":"user2",
  "password":"pass2",
  "roles":"{USER}"
}

### Добавление пользователя
###
POST http://localhost:9999/api/users
Content-Type: application/json

{
  "login":"user3",
  "password":"pass3",
  "roles":"{USER}"
}

### Добавление кривого пользователя
###
POST http://localhost:9999/api/users
Content-Type: application/json

{
  "login":"",
  "password":"pass1"
}

### Кривой URL
###
POST http://localhost:9999/api/userrrr
Content-Type: application/json

{
  "login":"user1",
  "password":"pass1"
}

### Запрос токена Admin
###
POST http://localhost:9999/api/token
Content-Type: application/json

{
  "login":"user1",
  "password":"pass1"
}

### Запрос токена User
###
POST http://localhost:9999/api/token
Content-Type: application/json

{
  "login":"user2",
  "password":"pass2"
}

### Запрос карт ADMIN
###
POST http://localhost:9999/api/getcards
Content-Type: application/json

{
  "token":"1e62ec2e-cb2a-4728-80f6-6d467d5f8ad8"
}

### Запрос карт USER
###
POST http://localhost:9999/api/getcards
Content-Type: application/json

{
  "token":"5c6d7950-9163-4152-b2a8-08001fa9c3b8"
}