

### Добавление пользователя
###
POST http://localhost:9999/api/users
Content-Type: application/json

{
  "login":"user1",
  "password":"pass1",
  "roles":"{ADMIN USER}"
}

### Добавление кривого пользователя
###
POST http://localhost:9999/api/users
Content-Type: application/json

{
  "login":"",
  "password":"pass1"
}

### Кривой URL
###
POST http://localhost:9999/api/userrrr
Content-Type: application/json

{
  "login":"user1",
  "password":"pass1"
}

### Запрос токена
###
POST http://localhost:9999/api/token
Content-Type: application/json

{
  "login":"user1",
  "password":"pass1"
}

### Запрос карт
###
POST http://localhost:9999/api/getcards
Content-Type: application/json

{
  "token":"$2a$04$UbNb.53ITxGx3H6tGtthqeAGR/Bfp79M5na2iNeYfVQp62K9a/5XO"
}